## SNOWFLAKE ##
## By default, the tool expects the profile name 'elementary'  ##
## This profile will be used for elementary's outputs. We      ##
## reccomend creating a dedicated database, or at least schema ##
elementary: 
  outputs:
    default:
      type: snowflake
      account: de88078.us-east-2.aws
        
      ## User/password auth, other options (Keypair/SSO) require other configs ##
      user: jongethomehelper
      password: qoxvyz-9mijgE-danpuj
      
      role: TRANSFORMER
      database: WEATHER
      warehouse: TRANSFORMING
      schema: WEATHER
      threads: 4
      ## OPTIONAL - if you want to create the lineage based on queries from more 
      ## than the last 7 days or you have 10k or more queries in the history pulled during 
      ## the requested dates range, add this parameter (NOTE: account_usage requires more permissions, see note below).
      query_history_source: account_usage