version: 2

sources:
  - name: knoema_noaa
    database: ENVIRONMENT_DATA_ATLAS
    schema: ENVIRONMENT
    tables:
      - name: NOAACD2019R
  - name: weather_tile
    database: WEATHERSOURCE_TILE_SAMPLE_SNOWFLAKE_SECURE_SHARE_1641488329256
    schema: STANDARD_TILE
    tables:
      - name: HISTORY_DAY
