version: 2

models:
  - name: town_temps_with_name
    columns: 
    - name: zip_code
      tests:
        - not_null
    config:
      edr:
        monitered: true

sources:
  - name: knoema_noaa
    database: ENVIRONMENT_DATA_ATLAS
    schema: ENVIRONMENT
    tables:
      - name: NOAACD2019R
  - name: weather_tile
    database: WEATHERSOURCE_TILE_SAMPLE_SNOWFLAKE_SECURE_SHARE_1641488329256
    schema: STANDARD_TILE
    tables:
      - name: HISTORY_DAY
  - name: fantasy_football
    database: FANTASY_FOOTBALL_2020
    schema: NFL2020
    tables:
      - name: SCHEDULE
      - name: PBP
      - name: TEAMS


